const fs = require('fs');
const path = require('path');

const OUTPUT_PATH = path.join(__dirname, '../src/version.ts');

function getDayOfYear(date) {
  const startOfYear = new Date(date.getFullYear(), 0, 0);
  const diff = date - startOfYear;
  const oneDay = 1000 * 60 * 60 * 24;
  return Math.floor(diff / oneDay);
}

function padZero(num) {
  return num < 10 ? '0' + num : '' + num;
}

// Get the current date and time
const now = new Date();

// Calculate Y (last 2 digits of current year)
const Y = now.getFullYear() % 100;

// Calculate doy (day number of the year)
const doy = getDayOfYear(now);

// Calculate b (concatenation of two-digit hour, minute, and second)
const hours = padZero(now.getHours());
const minutes = padZero(now.getMinutes());
const seconds = padZero(now.getSeconds());
const b = `${hours}${minutes}${seconds}`; // e.g., "102326" for 10:23:26 AM

const versionContent = `
// This file is automatically generated by scripts/generate-version.js
// Do not modify this file directly.

export const appVersion = {
  Y: ${Y},
  doy: ${doy},
  b: '${b}',
  full: '${Y}.${doy}.${b}'
};
`;

// Ensure the output directory exists
fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
// Write the version file
fs.writeFileSync(OUTPUT_PATH, versionContent, 'utf8');

console.log(`Generated version file: ${OUTPUT_PATH}`);
console.log(`Version: ${Y}.${doy}.${b}`);